services:
  mongo:
    image: mongo
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    environment:
      - MONGODB_URL=mongodb://mongo:27017/app
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    ports:
      - "8080:80"

volumes:
  mongo_data:
